### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by lechten** [timothypratley/asciidoctor-revealjs-klipse#8]
Many thanks for your work on integrating klipse with reveal.js! Your settings helped me a lot in my own project. I'm using a snippet [over there](https://gitlab.com/oer/org-re-reveal/blob/master/org-re-reveal.el#L931).

Now I'm wondering: Is this actually free/libre and open source software? If so, under what license?

**Comment by timothypratley** [comment]
Hi @lechten great, I am glad it helped :)

That is really cool what you have created in org-re-reveal.
Yes this project is public domain that you can snip and use freely.
Thank you for letting me know that it helped in your project, that is very encouraging.

I am happy to include a license to make it clearly free/libre.
Klipse uses (GNU General Public License v3.0),
revealjs uses MIT license
asciidoctor uses MIT license

I am no license expert so intend to include the MIT license as that seems appropriate here.
What do you think?

**Comment by lechten** [comment]
Cool, I was hoping that this was free software. Thanks!

I'm not sure where license experts exist :wink:  Combining licenses is challenging. If had a free wish here, I'd vote for GPLv3 as that is what I'm using. I'll add whatever license you choose, though.

**Comment by lechten** [comment]
One further question: In the README, you write about overriding CSS so that "clicking on the last line doesn’t scroll weirdly". So far, I'm not using that. Is there a way to reproduce the issue you are avoiding?

**Comment by timothypratley** [comment]
Hi Jens,

One example that causes "clicking on the last line doesn't scroll weirdly"
is:

== Large ClojureScript

[source.eval-clojure, clojure]
(defn greet [person]
  (str "Hello " person))
(map greet ["Alice" "Bob" "Carol"])


^^ When you click to edit the source code here, the text will "jump" up a
little bit.
Adding the CSS override fixes that.

GPL 3 sounds fine to me! I'll add that now :)

**Comment by timothypratley** [comment]
<img width="1200" alt="Screen Shot 2019-08-25 at 6 25 40 AM" src="https://user-images.githubusercontent.com/49298/63650608-3b949a00-c701-11e9-9a7c-65e031f32f8a.png">
For reference here is an image of what happens without the override: as you can see there is too much padding on the last line after clicking into the text box.

**Comment by lechten** [comment]
Many thanks for adding the license and also for taking the time to provide an example! I'll check that out for my own project later on.

**Comment by timothypratley** [comment]
my pleasure, thank you for reporting it
